<table>
    <thead>
        <th>Name</th>
        <th>Company</th>
        <th>Address</th>
    </thead>
    <tbody>
        <?php foreach ($this->article as $article) :?>
        <tr>
            <td><?php echo $article->getFullName(); ?></td>    
            <td><?php echo $article->getAddress(); ?></td>    
            <td><?php echo $article->getCompany(); ?></td>    
        </tr>
        <?php endforeach;?>
    </tbody>
</table>